version: '3.8'
services:
  affarituoi-app:
    image: openjdk:17-jdk
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    command: ./mvnw spring-boot:run
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    privileged: true

